name: Build and Test with latest V

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
          path: v

      - name: Build V
        run: cd v && make && sudo ./v symlink && cd -

      - name: V doctor
        run: v doctor

      - name: Checkout msgpack
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Symlink msgpack
        run: mkdir -p ~/.vmodules/ ; ln -s $(realpath repo) ~/.vmodules/msgpack

      - name: Ensure everything is formatted
        run: v fmt -verify ~/.vmodules/msgpack/

      - name: Ensure docs is OK
        run: v check-md ~/.vmodules/msgpack/README.md

      - name: Ensure all examples compile with -W
        run: v -W should-compile-all ~/.vmodules/msgpack/examples/

      - name: Run basic example with -Wimpure-v
        run: v -Wimpure-v crun ~/.vmodules/msgpack/examples/basic.v

      - name: Run bench example
        run: v run ~/.vmodules/msgpack/examples/bench_msgpack_json_vs_json2.v

      - name: Run example with -prod -cstrict -Wimpure-v -cc clang
        run: |
            cd ~/.vmodules/msgpack
            v -prod -cstrict -Wimpure-v -cc clang crun examples/basic.v
